### ISSUE TITLE
Formatierung Text "MQTT" auf Display 

### ISSUE THREAD

**Issue by fromCologne** [rancilio-pid/ranciliopid#137]
Hallo Team,

ich verwende:
DISPLAY = 1
DISPLAYTEMPLATE = 1
DISPLAYROTATE = U8G2_R0

Bei einem Kaltstart (auf dem Display die Kaffeemaschine) ist in der Statuszeile oben der Text "MQTT" in zu großer Schriftart.
Zu beheben mit display.h hinter Zeile 171 zufügen: u8g2.setFont(u8g2_font_profont11_tf);

Der Text "MQTT" ist auch etwas nach unten verrutscht. Hier hilft display.h in Zeile 201 und 205 jeweils zu ändern auf: u8g2.setCursor(77, 1);

Auch in Displaytemplatestandard.h muß der Text "MQTT" ein Pixel nach oben. Zeile 140 und 143. Änderung siehe oben.

Wer ein anderes DISPLAYTEMPLATE verwendet, muss die entsprechende Header-Datei anpassen.

**Comment by fiendie** [comment]
@fromCologne: Sollte mit https://github.com/rancilio-pid/ranciliopid/pull/220 im Alpha branch behoben sein
