### ISSUE TITLE
ZACwire

### ISSUE THREAD

**Issue by sagge86** [rancilio-pid/ranciliopid#207]
Hey, ich bekomme bei folgender Line den folgenden Fehler:

ZACwire<ONE_WIRE_BUS> Sensor2(306);    // set pin "2" to receive signal from the TSic "306"

--> 'ZACwire' is not a template

Woran liegt das?

**Comment by fiendie** [comment]
Womit kompilierst Du denn den Code?
In einer neueren Version der ZACWire Lib werden keine Templates mehr verwendet.

Das klingt so, als wolltest Du den Code aus dem master mit PlatformIO bauen?
Wenn ja, was steht denn in der platformio.ini?

Danke schonmal.

**Comment by sagge86** [comment]
Ich verwende die aktuelle Version der Arduino IDE (1.8.19 für Mac)
