### ISSUE TITLE
Alpha not prepared for scale users

### ISSUE THREAD

**Issue by cottec** [rancilio-pid/ranciliopid#216]
When using a scale the default sample rate value in the HX711_ADC library is unusable
HX711_ADC-1.2.7\src\config.h
line 27:
#define SAMPLES 					2		//default value: 16

value 16 is way too slow (it's more acurate, but thats really not needed in our application)

In addition currently the calibration of the scale is stored in the brewscaleini.h
line 39:
float calibrationValue = 545.00; // use calibration example to get value

this should be in the userconfig

**Comment by fiendie** [comment]
@cottec: Please try again with the latest commit in the alpha branch. https://github.com/rancilio-pid/ranciliopid/pull/217

**Comment by cottec** [comment]
Works great :) thanks
