### ISSUE TITLE
Clear SSID Lable for Wifimanager

### ISSUE THREAD

**Issue by LoQue90** [rancilio-pid/ranciliopid#248]
The SSID of the Ad-Hoc Wifi network that the ESP is sending on first boot, produced from the Wifimanger should have a clear name.
Right now the SSID ist something like "ESP-XXXXX"
A clear name e.x. "CleverCoffeeESP" or CleverCoffeeWifimanager" would give a obvious choice in the list of available Wifi networks.

**Comment by kjyv** [comment]
This works fine for me (at least on PR #253), it might be because of commit 0f66f6c

**Comment by murmeltier08** [comment]
solved
