### ISSUE TITLE
Pid Values out of range

### ISSUE THREAD

**Issue by cottec** [rancilio-pid/ranciliopid#270]
Quickmill uses a cold start Kp of 250 which is out of defined parameter range

**Comment by Alcoinus** [comment]
The issue should be the following line:

https://github.com/rancilio-pid/ranciliopid/blob/9bb3816a4f0c485dc99e01975b2b5ae1dbef0629/src/rancilio-pid.h#L38

As I am in no position to propose a new general value for this parameter, I am not opening a pull request. But you can change it locally to whatever suits you (>=250 I guess).

**Comment by cottec** [comment]
#272

**Comment by murmeltier08** [comment]
solved
