### ISSUE TITLE
When in Steam Mode the setpoint offset should be added to the setpoint

### ISSUE THREAD

**Issue by cottec** [rancilio-pid/ranciliopid#274]
Setpoint without the offset added seems just irritating

**Comment by kjyv** [comment]
I've actually specifically removed the offset because of safety threshold etc. Also the steam temperature does not have an offset in relation to the brew group, you get the steam temperature directly from the boiler so it actually doesn't make much sense to use the set offset there.

**Comment by murmeltier08** [comment]
solved
