### ISSUE TITLE
esp32 support? k-type thermistors?

### ISSUE THREAD

**Issue by creisey** [rancilio-pid/ranciliopid#32]
hi there

im superhappy that i found this distro!

i've planed since a long time to add PID to my Quickmill 3035.

my aim is to keep the Machine as close as possible to stock, so everything hidden and maybe only an exposing antenna to configure and monitor the temp.

is this distro also working with the ESP32? i just found the esp32 branch.. 👍 

and how hard is it to add K-Type Thermistors? with MAX6675 or MAX31855 ?

cheers

**Comment by btotherunner** [comment]
Hey, I'm glad you like it.
Adaptation to ESP32 is possible.
You can of course also use other thermal sensors.
The whole thing is kept very open.
It's best to come and see us in the chat.
https://chat.rancilio-pid.de
