### ISSUE TITLE
ShotTimer

### ISSUE THREAD

**Issue by btotherunner** [rancilio-pid/ranciliopid#38]
Wäre es möglich einen ShoTimer zu integrieren?

Damit auf dem Display auch bei der Brüherkennung der Shottimer startet und die Sekunden "Groß" angezeigt werden.

**Comment by murmeltier08** [comment]
Wollen wir das per Ini aktivierbar machen?

**Comment by btotherunner** [comment]
ja wäre super!

**Comment by murmeltier08** [comment]
Dann bau ich mal sowas ein bei Gelegenheit

**Comment by murmeltier08** [comment]
Idee: gleichzeitig BD nur noch +/- 1 am Sollpunkt aktivieren.

**Comment by ben-coe** [comment]
Könnte man hier direkt auch die Anzeige des Shottimers einige Sekunden stehen lassen (bei Hardware brewdetection), damit man sieht wie lange der Bezug gedauert hat?

**Comment by murmeltier08** [comment]
Erste Version ist umgesetzt!

**Comment by rasimriver** [comment]
Ich wollte den Shottimer testen, habe ihn aber wieder deaktivert. Jetzt scheine ich ein Bug zu haben: Der Shottimer flackert nun ständig neu auf. Muss man hier beim Hochladen etwas beachten?

**Comment by murmeltier08** [comment]
Das sollte eigentlich nicht sein. Könntest du deine Display Config dazu zeigen?

**Comment by rasimriver** [comment]
Ja, ich habe den aktuellsten commit verwendet. Die Userconfig habe ich auf Mattermost gepostet [Link](https://chat.rancilio-pid.de/ranciliopid/pl/5rk6zn43rinnxm8cpoh5r9hihr)

**Comment by murmeltier08** [comment]
Ich habe den Fehler gefunden: der Shottimer war vorher auf Ebene vom "oder", jetzt sollte es gehen

```
         (
            (bezugsZeit > 0 && ONLYPID == 1) || // Bezugszeit bei Only PID  
            (ONLYPID == 0 && brewcounter > 10 && brewcounter <= 42) // oder Bezug bei nicht only PID über brewcounter
            ) && SHOTTIMER == 1
```

**Comment by murmeltier08** [comment]
Problem hoffentlich gelöst im aktuellen Push, bei mir geht es. Sonst melde dich bitte @rasimriver
