### ISSUE TITLE
"Displayrotateupright.h" missing variable declaration

### ISSUE THREAD

**Issue by Extraweich** [rancilio-pid/ranciliopid#401]
The variables "machineLogo" and "brewTime_last_Millis" are not set in "Displayrotateupright.h", preventing the user to use the vertical display design, if they set "DISPLAYTEMPLAE" to 20 in the "userConfig.h". Also the Docs refer to the "git Handbook" if the user is interested in such, but I cannot find this. It seems like this display template is not expected to be used anymore, but it is still part of the newest firmware.

**Comment by fiendie** [comment]
To be fair, I suspect it's not that widely used but you're right: if it's there it should work. We'll look into it 😉

**Comment by LoQue90** [comment]
should work again on V3.3.0
will be added to master V4.0 also
