### ISSUE TITLE
Licht wenn Temperatur erreicht ist +-5 °C

### ISSUE THREAD

**Issue by hansgans007** [rancilio-pid/ranciliopid#56]
Einen Ausgang schalten wenn die Temperatur erreicht ist :)

**Comment by murmeltier08** [comment]
Welchen Ausgang genau?

**Comment by hansgans007** [comment]
ich hab derweil auf 16 geklemmt ETRIGGER oder wie der heißt brauch ich eh nicht

**Comment by murmeltier08** [comment]
Reicht dir ein HIGH oder noch was? 
HIGH kleiner 5 Grad
LOW größer 5 Grad

**Comment by hansgans007** [comment]
Ja das passt im mittel einfach +-5 grad wäre klasse

**Comment by tml89** [comment]
Ist diese funktion bereits implementiert? Plane gerade einen Umbau ohne Display und möchte auch nicht den PERFECT COFFEE PID Fork nutzen.

**Comment by murmeltier08** [comment]
Melde dich gerne mal im chat bei uns. das sollte sich schnell einbauen lassen. Dann besprechen wir das gerne im Detail

**Comment by murmeltier08** [comment]
Ist in der Alpha 3.0.0 nun drin 
PINLED und LEDON muss in der konfig gesetzt werden
