### ISSUE TITLE
Update ZACwire Library

### ISSUE THREAD

**Issue by lebuni** [rancilio-pid/ranciliopid#91]
In the last weeks I developed and tested a new version of the ZACwire Library for the TSic temperature sensor. The changes are the following:

- works also on an ESP32 or other µC
- checks with every `.getTemp()`, if the sensor is still connected and sending
- scattered reading errors have been eliminated
- ISR is faster

Please update the library files to the 1.3.0:
[https://github.com/lebuni/ZACwire-Library](https://github.com/lebuni/ZACwire-Library)

**Comment by murmeltier08** [comment]
I will test it with my esp32 in the next days

**Comment by murmeltier08** [comment]
In 2.9.0
