### ISSUE TITLE
constant reboots of current master (2.8.1) on ESP32 due to high system load

### ISSUE THREAD

**Issue by andreas301-sketch** [rancilio-pid/ranciliopid#94]
With the current master I get constant reboots on an ESP32. The reason seems to be invalid values from the TSIC, which trigger the restart. The underlying cause for that might be high system load. If DEBUGMODE is disabled (enabled by default), the reboots are gone.

**Comment by murmeltier08** [comment]
Fix in 2.9.0. There was a bug by the ISR debug message
